/* eslint-disable no-console */
import Head from "next/head";
import Image from "next/image";
import {useState} from "react";

import styles from "../styles/Home.module.css";
import form from "../styles/Form.module.css";

export default function App() {
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [message, setMessage] = useState("");

  const handleSubmit = (e) => {
    e.preventDefault();
    console.log("Sending");

    let data = {
      name,
      email,
      message,
    };

    fetch("/api/contact", {
      method: "POST",
      headers: {
        Accept: "application/json, text/plain, */*",
        "Content-Type": "application/json",
      },
      body: JSON.stringify(data),
    })
      .then((res) => {
        return res.json();
      })
      .then((res) => {
        console.log("Response received");
        if (res.status === 200) {
          console.log("Response succeeded!");
          setSubmitted(true);
          setName("");
          setEmail("");
        }
      });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <h1>Practice - Next with Nodemailer</h1>
        <h2>Data form</h2>
        <div className={form.container}>
          <form className={form.main}>
            <div className={form.inputGroup}>
              <label htmlFor="name">Nombre</label>
              <input
                className={form.inputField}
                id="name"
                name="name"
                placeholder="Escriba su nombre aqui"
                type="text"
                onChange={(e) => {
                  setName(e.target.value);
                }}
              />
            </div>
            <div className={form.inputGroup}>
              <label htmlFor="email">Correo electronico</label>
              <input
                className={form.inputField}
                id="name"
                name="email"
                placeholder="Escriba su nombre correo electronico"
                type="email"
                onChange={(e) => {
                  setEmail(e.target.value);
                }}
              />
            </div>
            <div className={form.inputGroup}>
              <label htmlFor="message">Mensaje</label>
              <textarea
                className={form.textarea}
                id="message"
                name="message"
                placeholder="Escriba su nombre mensaje"
                onChange={(e) => {
                  setMessage(e.target.value);
                }}
              />
            </div>
            <button
              type="submit"
              onClick={(e) => {
                handleSubmit(e);
              }}
            >
              Enviar datos
            </button>
          </form>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          rel="noopener noreferrer"
          target="_blank"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image alt="Vercel Logo" height={16} src="/vercel.svg" width={72} />
          </span>
        </a>
      </footer>
    </div>
  );
}
